name: Multi-Platform Build

on:
  workflow_dispatch:
    inputs:
      platforms:
        description: '选择要构建的平台（可多选）'
        type: choice
        options:
        - all
        - linux-x64
        - linux-arm64
        - windows-x64
        - android
        required: true
        default: 'linux-x64'
        multiple: true

jobs:
  build-linux-x64:
    name: Build Linux x64
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.inputs.platforms, 'all') || contains(github.event.inputs.platforms, 'linux-x64') }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --name SocketChatApp-linux-x64 main.py

    - name: Upload Linux x64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: socketchatapp-linux-x64
        path: dist/SocketChatApp-linux-x64
        retention-days: 30

  build-linux-arm64:
    name: Build Linux ARM64
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.inputs.platforms, 'all') || contains(github.event.inputs.platforms, 'linux-arm64') }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --name SocketChatApp-linux-arm64 main.py

    - name: Upload Linux ARM64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: socketchatapp-linux-arm64
        path: dist/SocketChatApp-linux-arm64
        retention-days: 30

  build-windows-x64:
    name: Build Windows x64
    runs-on: windows-latest
    if: ${{ contains(github.event.inputs.platforms, 'all') || contains(github.event.inputs.platforms, 'windows-x64') }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --name SocketChatApp-windows-x64 --console main.py

    - name: Upload Windows x64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: socketchatapp-windows-x64
        path: dist/SocketChatApp-windows-x64.exe
        retention-days: 30

  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.inputs.platforms, 'all') || contains(github.event.inputs.platforms, 'android') }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Buildozer and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer
        pip install -r requirements.txt
        pip install cython  # 添加Cython依赖
        sudo apt-get update
        sudo apt-get install -y git unzip openjdk-11-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev

    - name: Validate buildozer.spec
      run: |
        echo "检查buildozer.spec文件..."
        if [ -f buildozer.spec ]; then
          echo "buildozer.spec文件存在，跳过初始化"
        else
          echo "buildozer.spec文件不存在，进行初始化"
          buildozer init
        fi

    - name: Build Android APK
      run: |
        buildozer -v android debug

    - name: Upload Android APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: socketchatapp-android
        path: bin/*.apk
        retention-days: 30